### ISSUE TITLE
Can't login because of 2FA

### ISSUE THREAD

**Issue by NebKi** [dumbasPL/deluge-windscribe-ephemeral-port#15]
Currently, it seems like logging in with an account that has been set up with 2FA is not possible. Can this be supported or entered manually or through a variable somehow?

**Comment by dumbasPL** [comment]
The windscribe sessions don't last long, so the only viable option would be to have the TOTP secret alongside the password and generate codes automatically because manually entering it all the time goes against the idea of automation. Keeping the TOTP right next to the password defeats the idea of 2fa (keyword: two factor). When you put the TOTP secret next to the password you essentially make the second factor pointless.

I could add it but it makes absolutely 0 sense to me. Let me know how you see this issue.

**Comment by NebKi** [comment]
You are right, if we would have to put in the master TOTP password that wouldn't be wise to do. I wonder what the expiry time is though, since I logged into the WS portal with 2FA once and since then I'm still logging in without 2FA. Maybe browser sessions last longer than application sessions. 

Was also thinking about copying the browser cookie, but couldn't match the format. I think disabling 2FA would be the easiest solution then. Thing is that WS seems to be tagging the frequent logins from the container as suspicious. So using 2FA would remove some of that suspicion, hopefully.  Will just low the frequency of the checks for now.

Thanks for thinking along!

**Comment by dumbasPL** [comment]
> Maybe browser sessions last longer than application sessions.

We are using the browser session though

> Thing is that WS seems to be tagging the frequent logins from the container as suspicious.

You can reduce the frequency by not enabling the corn job, this way it will only log in once a week + on container restarts. Cookies are also cached so it won't log in until they expire. Maybe something broke? I haven't had any issues personally

**Comment by NebKi** [comment]
Thanks, didn't know that was possible. I have removed the cron job and all is working again. I just hope WS won't flag me again. Can't be 100% sure it was this, of course, but it's the only tool using the VPN together with Deluge.

Thanks for the help and the software :)
